name: Backend Lint
on: [push, pull_request]
jobs:
  backend-lint:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: ['5.0']

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      working-directory: jobservatory_express
      run: npm install
    - name: Run ESLint
      working-directory: jobservatory_express
      run: npm run linter